### ISSUE TITLE
build css from design token

### ISSUE THREAD

**Issue by kimpra2989** [kimpra2989/monorepo-pra#1]
### js 객체로 주어진 디자인 토큰을 node script를 통해 css variable로 빌드합니다.

**요구사항
- css variable인 ```:root```가  class 보다 먼저 정의 되어야합니다.
- ```blackAlpha``` 혹은 ```fontSize```처러 카멜## js 객체로 주어진 디자인 토큰을 node script를 통해 css variable로 빌드합니다.

**요구사항
- css variable인 ```:root```가  class 보다 먼저 정의 되어야 합니다.
- 다크 모드 색상의 경우 ```:root .theme-dark``` 내부에 선언되여야 합니다.
- ```:root```내부의 변수들은 css variable 형태로 표기 되어야합니다. ( e. g. --radii-none: 0 )
- ```blackAlpha``` 혹은 ```fontSize```처럼 표기된 카멜케이스 스타일 속성명을 케밥케이스로 변환해야 합니다. ( e. g. fontSize => --font-size )

**raw data**
```js
  classes: {
    typography: {
      heading: {
        '4xl': {
          fontSize: '3.75rem',
          fontWeight: '700',
          lineHeight: '100%',
        },
        '3xl': {
          fontSize: '3rem',
          fontWeight: '700',
          lineHeight: '100%',
        },
        '2xl': {
          fontSize: '2.25rem',
          fontWeight: '700',
          lineHeight: '120%',
        },
        xl: {
          fontSize: '1.875rem',
          fontWeight: '700',
          lineHeight: '133%',
        },
        lg: {
          fontSize: '1.5rem',
          fontWeight: '700',
          lineHeight: '133%',
        },
        md: {
          fontSize: '1.25rem',
          fontWeight: '700',
          lineHeight: '120%',
        },
        sm: { fontSize: '1rem', fontWeight: '700', lineHeight: '120%' },
        xs: {
          fontSize: '0.875rem',
          fontWeight: '700',
          lineHeight: '120%',
        },
      },
      text: {
        '6xl': {
          fontSize: '3.75rem',
          fontWeight: '400',
          lineHeight: '150%',
        },
        '5xl': {
          fontSize: '3rem',
          fontWeight: '400',
          lineHeight: '150%',
        },
        '4xl': {
          fontSize: '2.25rem',
          fontWeight: '400',
          lineHeight: '150%',
        },
        '3xl': {
          fontSize: '1.875rem',
          fontWeight: '400',
          lineHeight: '150%',
        },
        '2xl': {
          fontSize: '1.5rem',
          fontWeight: '400',
          lineHeight: '150%',
        },
        xl: {
          fontSize: '1.25rem',
          fontWeight: '400',
          lineHeight: '150%',
        },
        lg: {
          fontSize: '1.125rem',
          fontWeight: '400',
          lineHeight: '150%',
        },
        md: { fontSize: '1rem', fontWeight: '400', lineHeight: '150%' },
        sm: {
          fontSize: '0.875rem',
          fontWeight: '400',
          lineHeight: '150%',
        },
        xs: {
          fontSize: '0.75rem',
          fontWeight: '400',
          lineHeight: '150%',
        },
      },
    },
  },
  vars: {
    box: {
      radii: {
        none: '0',
        sm: '0.125rem',
        base: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      shadows: {
        xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
        sm: '0px 1px 2px 0px rgba(0, 0, 0, 0.05)',
        base: '0px 1px 2px 0px rgba(0, 0, 0, 0.06), 0px 1px 3px 0px rgba(0, 0, 0, 0.10)',
        md: '0px 2px 4px -1px rgba(0, 0, 0, 0.06), 0px 4px 6px -1px rgba(0, 0, 0, 0.10)',
        lg: '0px 4px 6px -2px rgba(0, 0, 0, 0.05), 0px 10px 15px -3px rgba(0, 0, 0, 0.10)',
        xl: '0px 10px 10px -5px rgba(0, 0, 0, 0.04), 0px 20px 25px -5px rgba(0, 0, 0, 0.10)',
        '2xl': '0px 25px 50px -12px rgba(0, 0, 0, 0.25)',
        inner: '0px 2px 4px 0px rgba(0, 0, 0, 0.06) inset',
        darkLg:
          '0px 15px 40px 0px rgba(0, 0, 0, 0.40), 0px 5px 10px 0px rgba(0, 0, 0, 0.20), 0px 0px 0px 1px rgba(0, 0, 0, 0.10)',
        outline: '0 0 0 3px rgba(66, 153, 225, 0.6)',
      },
      spacing: {
        0: '0',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        11: '2.75rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        28: '7rem',
        32: '8rem',
        36: '9rem',
        40: '10rem',
        44: '11rem',
        48: '12rem',
        52: '13rem',
        56: '14rem',
        60: '15rem',
        64: '16rem',
        72: '18rem',
        80: '20rem',
        96: '24rem',
      },
    },
    colors: {
      $scale: {
        blackAlpha: {
          50: 'var(--black-alpha-50)',
          100: 'var(--black-alpha-100)',
          200: 'var(--black-alpha-200)',
          300: 'var(--black-alpha-300)',
          400: 'var(--black-alpha-400)',
          500: 'var(--black-alpha-500)',
          600: 'var(--black-alpha-600)',
          700: 'var(--black-alpha-700)',
          800: 'var(--black-alpha-800)',
          900: 'var(--black-alpha-900)',
        },
        blue: {
          50: 'var(--blue-50)',
          100: 'var(--blue-100)',
          200: 'var(--blue-200)',
          300: 'var(--blue-300)',
          400: 'var(--blue-400)',
          500: 'var(--blue-500)',
          600: 'var(--blue-600)',
          700: 'var(--blue-700)',
          800: 'var(--blue-800)',
          900: 'var(--blue-900)',
        },
        cyan: {
          50: 'var(--cyan-50)',
          100: 'var(--cyan-100)',
          200: 'var(--cyan-200)',
          300: 'var(--cyan-300)',
          400: 'var(--cyan-400)',
          500: 'var(--cyan-500)',
          600: 'var(--cyan-600)',
          700: 'var(--cyan-700)',
          800: 'var(--cyan-800)',
          900: 'var(--cyan-900)',
        },
        gray: {
          50: 'var(--gray-50)',
          100: 'var(--gray-100)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          400: 'var(--gray-400)',
          500: 'var(--gray-500)',
          600: 'var(--gray-600)',
          700: 'var(--gray-700)',
          800: 'var(--gray-800)',
          900: 'var(--gray-900)',
        },
        green: {
          50: 'var(--green-50)',
          100: 'var(--green-100)',
          200: 'var(--green-200)',
          300: 'var(--green-300)',
          400: 'var(--green-400)',
          500: 'var(--green-500)',
          600: 'var(--green-600)',
          700: 'var(--green-700)',
          800: 'var(--green-800)',
          900: 'var(--green-900)',
        },
        orange: {
          50: 'var(--orange-50)',
          100: 'var(--orange-100)',
          200: 'var(--orange-200)',
          300: 'var(--orange-300)',
          400: 'var(--orange-400)',
          500: 'var(--orange-500)',
          600: 'var(--orange-600)',
          700: 'var(--orange-700)',
          800: 'var(--orange-800)',
          900: 'var(--orange-900)',
        },
        pink: {
          50: 'var(--pink-50)',
          100: 'var(--pink-100)',
          200: 'var(--pink-200)',
          300: 'var(--pink-300)',
          400: 'var(--pink-400)',
          500: 'var(--pink-500)',
          600: 'var(--pink-600)',
          700: 'var(--pink-700)',
          800: 'var(--pink-800)',
          900: 'var(--pink-900)',
        },
        purple: {
          50: 'var(--purple-50)',
          100: 'var(--purple-100)',
          200: 'var(--purple-200)',
          300: 'var(--purple-300)',
          400: 'var(--purple-400)',
          500: 'var(--purple-500)',
          600: 'var(--purple-600)',
          700: 'var(--purple-700)',
          800: 'var(--purple-800)',
          900: 'var(--purple-900)',
        },
        red: {
          50: 'var(--red-50)',
          100: 'var(--red-100)',
          200: 'var(--red-200)',
          300: 'var(--red-300)',
          400: 'var(--red-400)',
          500: 'var(--red-500)',
          600: 'var(--red-600)',
          700: 'var(--red-700)',
          800: 'var(--red-800)',
          900: 'var(--red-900)',
        },
        teal: {
          50: 'var(--teal-50)',
          100: 'var(--teal-100)',
          200: 'var(--teal-200)',
          300: 'var(--teal-300)',
          400: 'var(--teal-400)',
          500: 'var(--teal-500)',
          600: 'var(--teal-600)',
          700: 'var(--teal-700)',
          800: 'var(--teal-800)',
          900: 'var(--teal-900)',
        },
        whiteAlpha: {
          50: 'var(--white-alpha-50)',
          100: 'var(--white-alpha-100)',
          200: 'var(--white-alpha-200)',
          300: 'var(--white-alpha-300)',
          400: 'var(--white-alpha-400)',
          500: 'var(--white-alpha-500)',
          600: 'var(--white-alpha-600)',
          700: 'var(--white-alpha-700)',
          800: 'var(--white-alpha-800)',
          900: 'var(--white-alpha-900)',
        },
        yellow: {
          50: 'var(--yellow-50)',
          100: 'var(--yellow-100)',
          200: 'var(--yellow-200)',
          300: 'var(--yellow-300)',
          400: 'var(--yellow-400)',
          500: 'var(--yellow-500)',
          600: 'var(--yellow-600)',
          700: 'var(--yellow-700)',
          800: 'var(--yellow-800)',
          900: 'var(--yellow-900)',
        },
      },
      $static: {
        dark: {
          blackAlpha: {
            50: 'rgba(0, 0, 0, 0.92)',
            100: 'rgba(0, 0, 0, 0.80)',
            200: 'rgba(0, 0, 0, 0.64)',
            300: 'rgba(0, 0, 0, 0.48)',
            400: 'rgba(0, 0, 0, 0.36)',
            500: 'rgba(0, 0, 0, 0.24)',
            600: 'rgba(0, 0, 0, 0.16)',
            700: 'rgba(0, 0, 0, 0.08)',
            800: 'rgba(0, 0, 0, 0.06)',
            900: 'rgba(0, 0, 0, 0.04)',
          },
          blue: {
            50: '#1A365D',
            100: '#2a4365',
            200: '#2c5282',
            300: '#2b6cb0',
            400: '#3182ce',
            500: '#4299e1',
            600: '#63b3ed',
            700: '#90cdf4',
            800: '#bee3f8',
            900: '#ebf8ff',
          },
          color: { black: '#000', white: '#fff' },
          cyan: {
            50: '#065666',
            100: '#086F83',
            200: '#0987A0',
            300: '#00A3C4',
            400: '#00B5D8',
            500: '#0BC5EA',
            600: '#76E4F7',
            700: '#9DECF9',
            800: '#C4F1F9',
            900: '#EDFDFD',
          },
          gray: {
            50: '#171923',
            100: '#1A202C',
            200: '#2D3748',
            300: '#4A5568',
            400: '#718096',
            500: '#A0AEC0',
            600: '#CBD5E0',
            700: '#E2E8F0',
            800: '#EDF2F7',
            900: '#F7FAFC',
          },
          green: {
            50: '#1C4532',
            100: '#22543D',
            200: '#276749',
            300: '#2F855A',
            400: '#38A169',
            500: '#48BB78',
            600: '#68D391',
            700: '#9AE6B4',
            800: '#C6F6D5',
            900: '#F0FFF4',
          },
          orange: {
            50: '#652B19',
            100: '#7B341E',
            200: '#9C4221',
            300: '#C05621',
            400: '#DD6B20',
            500: '#ED8936',
            600: '#F6AD55',
            700: '#FBD38D',
            800: '#FEEBC8',
            900: '#FFFAF0',
          },
          pink: {
            50: '#521B41',
            100: '#702459',
            200: '#97266D',
            300: '#B83280',
            400: '#D53F8C',
            500: '#ED64A6',
            600: '#F687B3',
            700: '#FBB6CE',
            800: '#FED7E2',
            900: '#FFF5F7',
          },
          purple: {
            50: '#322659',
            100: '#44337A',
            200: '#553C9A',
            300: '#6B46C1',
            400: '#805AD5',
            500: '#9F7AEA',
            600: '#B794F4',
            700: '#D6BCFA',
            800: '#E9D8FD',
            900: '#FAF5FF',
          },
          red: {
            50: '#63171B',
            100: '#822727',
            200: '#9B2C2C',
            300: '#C53030',
            400: '#E53E3E',
            500: '#F56565',
            600: '#FC8181',
            700: '#FEB2B2',
            800: '#FED7D7',
            900: '#FFF5F5',
          },
          teal: {
            50: '#1D4044',
            100: '#234E52',
            200: '#285E61',
            300: '#2C7A7B',
            400: '#319795',
            500: '#38B2AC',
            600: '#4FD1C5',
            700: '#81E6D9',
            800: '#B2F5EA',
            900: '#E6FFFA',
          },
          whiteAlpha: {
            50: 'rgba(255, 255, 255, 0.92)',
            100: 'rgba(255, 255, 255, 0.80)',
            200: 'rgba(255, 255, 255, 0.64)',
            300: 'rgba(255, 255, 255, 0.48)',
            400: 'rgba(255, 255, 255, 0.36)',
            500: 'rgba(255, 255, 255, 0.24)',
            600: 'rgba(255, 255, 255, 0.16)',
            700: 'rgba(255, 255, 255, 0.08)',
            800: 'rgba(255, 255, 255, 0.06)',
            900: 'rgba(255, 255, 255, 0.04)',
          },
          yellow: {
            50: '#5F370E',
            100: '#744210',
            200: '#975A16',
            300: '#B7791F',
            400: '#D69E2E',
            500: '#ECC94B',
            600: '#F6E05E',
            700: '#FAF089',
            800: '#FEFCBF',
            900: '#FFFFF0',
          },
        },
        light: {
          blackAlpha: {
            50: 'rgba(0, 0, 0, 0.04)',
            100: 'rgba(0, 0, 0, 0.06)',
            200: 'rgba(0, 0, 0, 0.08)',
            300: 'rgba(0, 0, 0, 0.16)',
            400: 'rgba(0, 0, 0, 0.24)',
            500: 'rgba(0, 0, 0, 0.36)',
            600: 'rgba(0, 0, 0, 0.48)',
            700: 'rgba(0, 0, 0, 0.64)',
            800: 'rgba(0, 0, 0, 0.80)',
            900: 'rgba(0, 0, 0, 0.92)',
          },
          blue: {
            50: '#ebf8ff',
            100: '#bee3f8',
            200: '#90cdf4',
            300: '#63b3ed',
            400: '#4299e1',
            500: '#3182ce',
            600: '#2b6cb0',
            700: '#2c5282',
            800: '#2a4365',
            900: '#1A365D',
          },
          color: { black: '#000', white: '#fff' },
          cyan: {
            50: '#EDFDFD',
            100: '#C4F1F9',
            200: '#9DECF9',
            300: '#76E4F7',
            400: '#0BC5EA',
            500: '#00B5D8',
            600: '#00A3C4',
            700: '#0987A0',
            800: '#086F83',
            900: '#065666',
          },
          gray: {
            50: '#F7FAFC',
            100: '#EDF2F7',
            200: '#E2E8F0',
            300: '#CBD5E0',
            400: '#A0AEC0',
            500: '#718096',
            600: '#4A5568',
            700: '#2D3748',
            800: '#1A202C',
            900: '#171923',
          },
          green: {
            50: '#F0FFF4',
            100: '#C6F6D5',
            200: '#9AE6B4',
            300: '#68D391',
            400: '#48BB78',
            500: '#38A169',
            600: '#2F855A',
            700: '#276749',
            800: '#22543D',
            900: '#1C4532',
          },
          orange: {
            50: '#FFFAF0',
            100: '#FEEBC8',
            200: '#FBD38D',
            300: '#F6AD55',
            400: '#ED8936',
            500: '#DD6B20',
            600: '#C05621',
            700: '#9C4221',
            800: '#7B341E',
            900: '#652B19',
          },
          pink: {
            50: '#FFF5F7',
            100: '#FED7E2',
            200: '#FBB6CE',
            300: '#F687B3',
            400: '#ED64A6',
            500: '#D53F8C',
            600: '#B83280',
            700: '#97266D',
            800: '#702459',
            900: '#521B41',
          },
          purple: {
            50: '#FAF5FF',
            100: '#E9D8FD',
            200: '#D6BCFA',
            300: '#B794F4',
            400: '#9F7AEA',
            500: '#805AD5',
            600: '#6B46C1',
            700: '#553C9A',
            800: '#44337A',
            900: '#322659',
          },
          red: {
            50: '#FFF5F5',
            100: '#FED7D7',
            200: '#FEB2B2',
            300: '#FC8181',
            400: '#F56565',
            500: '#E53E3E',
            600: '#C53030',
            700: '#9B2C2C',
            800: '#822727',
            900: '#63171B',
          },
          teal: {
            50: '#E6FFFA',
            100: '#B2F5EA',
            200: '#81E6D9',
            300: '#4FD1C5',
            400: '#38B2AC',
            500: '#319795',
            600: '#2C7A7B',
            700: '#285E61',
            800: '#234E52',
            900: '#1D4044',
          },
          whiteAlpha: {
            50: 'rgba(255, 255, 255, 0.04)',
            100: 'rgba(255, 255, 255, 0.06)',
            200: 'rgba(255, 255, 255, 0.08)',
            300: 'rgba(255, 255, 255, 0.16)',
            400: 'rgba(255, 255, 255, 0.24)',
            500: 'rgba(255, 255, 255, 0.36)',
            600: 'rgba(255, 255, 255, 0.48)',
            700: 'rgba(255, 255, 255, 0.64)',
            800: 'rgba(255, 255, 255, 0.80)',
            900: 'rgba(255, 255, 255, 0.92)',
          },
          yellow: {
            50: '#FFFFF0',
            100: '#FEFCBF',
            200: '#FAF089',
            300: '#F6E05E',
            400: '#ECC94B',
            500: '#D69E2E',
            600: '#B7791F',
            700: '#975A16',
            800: '#744210',
            900: '#5F370E',
          },
        },
      },
    },
    typography: {
      fontSize: {
        12: '0.75rem',
        14: '0.875rem',
        16: '1rem',
        18: '1.125rem',
        20: '1.25rem',
        24: '1.5rem',
        30: '1.875rem',
        36: '2.25rem',
        48: '3rem',
        60: '3.75rem',
        72: '4.5rem',
      },
      fontWeight: { 400: '400', 500: '500', 600: '600', 700: '700' },
      lineHeight: {
        100: '100%',
        120: '120%',
        133: '133%',
        150: '150%',
      },
    },
  },
```

**css**
```css
:root {
--radii-none: 0;
--radii-sm: 0.125rem;
--radii-base: 0.25rem;
--radii-md: 0.375rem;
--radii-lg: 0.5rem;
--radii-xl: 0.75rem;
--radii-2xl: 1rem;
--radii-3xl: 1.5rem;
--radii-full: 9999px;
--shadows-xs: 0 0 0 1px rgba(0, 0, 0, 0.05);
--shadows-sm: 0px 1px 2px 0px rgba(0, 0, 0, 0.05);
--shadows-base: 0px 1px 2px 0px rgba(0, 0, 0, 0.06), 0px 1px 3px 0px rgba(0, 0, 0, 0.10);
--shadows-md: 0px 2px 4px -1px rgba(0, 0, 0, 0.06), 0px 4px 6px -1px rgba(0, 0, 0, 0.10);
--shadows-lg: 0px 4px 6px -2px rgba(0, 0, 0, 0.05), 0px 10px 15px -3px rgba(0, 0, 0, 0.10);
--shadows-xl: 0px 10px 10px -5px rgba(0, 0, 0, 0.04), 0px 20px 25px -5px rgba(0, 0, 0, 0.10);
--shadows-2xl: 0px 25px 50px -12px rgba(0, 0, 0, 0.25);
--shadows-inner: 0px 2px 4px 0px rgba(0, 0, 0, 0.06) inset;
--shadows-dark-lg: 0px 15px 40px 0px rgba(0, 0, 0, 0.40), 0px 5px 10px 0px rgba(0, 0, 0, 0.20), 0px 0px 0px 1px rgba(0, 0, 0, 0.10);
--shadows-outline: 0 0 0 3px rgba(66, 153, 225, 0.6);
--spacing-0: 0;
--spacing-1: 0.25rem;
--spacing-2: 0.5rem;
--spacing-3: 0.75rem;
--spacing-4: 1rem;
--spacing-5: 1.25rem;
--spacing-6: 1.5rem;
--spacing-7: 1.75rem;
--spacing-8: 2rem;
--spacing-9: 2.25rem;
--spacing-10: 2.5rem;
--spacing-11: 2.75rem;
--spacing-12: 3rem;
--spacing-14: 3.5rem;
--spacing-16: 4rem;
--spacing-20: 5rem;
--spacing-24: 6rem;
--spacing-28: 7rem;
--spacing-32: 8rem;
--spacing-36: 9rem;
--spacing-40: 10rem;
--spacing-44: 11rem;
--spacing-48: 12rem;
--spacing-52: 13rem;
--spacing-56: 14rem;
--spacing-60: 15rem;
--spacing-64: 16rem;
--spacing-72: 18rem;
--spacing-80: 20rem;
--spacing-96: 24rem;
}
:root .theme-dark {
--black-alpha-50: rgba(0, 0, 0, 0.92);
--black-alpha-100: rgba(0, 0, 0, 0.80);
--black-alpha-200: rgba(0, 0, 0, 0.64);
--black-alpha-300: rgba(0, 0, 0, 0.48);
--black-alpha-400: rgba(0, 0, 0, 0.36);
--black-alpha-500: rgba(0, 0, 0, 0.24);
--black-alpha-600: rgba(0, 0, 0, 0.16);
--black-alpha-700: rgba(0, 0, 0, 0.08);
--black-alpha-800: rgba(0, 0, 0, 0.06);
--black-alpha-900: rgba(0, 0, 0, 0.04);
--blue-50: #1A365D;
--blue-100: #2a4365;
--blue-200: #2c5282;
--blue-300: #2b6cb0;
--blue-400: #3182ce;
--blue-500: #4299e1;
--blue-600: #63b3ed;
--blue-700: #90cdf4;
--blue-800: #bee3f8;
--blue-900: #ebf8ff;
--color-black: #000;
--color-white: #fff;
--cyan-50: #065666;
--cyan-100: #086F83;
--cyan-200: #0987A0;
--cyan-300: #00A3C4;
--cyan-400: #00B5D8;
--cyan-500: #0BC5EA;
--cyan-600: #76E4F7;
--cyan-700: #9DECF9;
--cyan-800: #C4F1F9;
--cyan-900: #EDFDFD;
--gray-50: #171923;
--gray-100: #1A202C;
--gray-200: #2D3748;
--gray-300: #4A5568;
--gray-400: #718096;
--gray-500: #A0AEC0;
--gray-600: #CBD5E0;
--gray-700: #E2E8F0;
--gray-800: #EDF2F7;
--gray-900: #F7FAFC;
--green-50: #1C4532;
--green-100: #22543D;
--green-200: #276749;
--green-300: #2F855A;
--green-400: #38A169;
--green-500: #48BB78;
--green-600: #68D391;
--green-700: #9AE6B4;
--green-800: #C6F6D5;
--green-900: #F0FFF4;
--orange-50: #652B19;
--orange-100: #7B341E;
--orange-200: #9C4221;
--orange-300: #C05621;
--orange-400: #DD6B20;
--orange-500: #ED8936;
--orange-600: #F6AD55;
--orange-700: #FBD38D;
--orange-800: #FEEBC8;
--orange-900: #FFFAF0;
--pink-50: #521B41;
--pink-100: #702459;
--pink-200: #97266D;
--pink-300: #B83280;
--pink-400: #D53F8C;
--pink-500: #ED64A6;
--pink-600: #F687B3;
--pink-700: #FBB6CE;
--pink-800: #FED7E2;
--pink-900: #FFF5F7;
--purple-50: #322659;
--purple-100: #44337A;
--purple-200: #553C9A;
--purple-300: #6B46C1;
--purple-400: #805AD5;
--purple-500: #9F7AEA;
--purple-600: #B794F4;
--purple-700: #D6BCFA;
--purple-800: #E9D8FD;
--purple-900: #FAF5FF;
--red-50: #63171B;
--red-100: #822727;
--red-200: #9B2C2C;
--red-300: #C53030;
--red-400: #E53E3E;
--red-500: #F56565;
--red-600: #FC8181;
--red-700: #FEB2B2;
--red-800: #FED7D7;
--red-900: #FFF5F5;
--teal-50: #1D4044;
--teal-100: #234E52;
--teal-200: #285E61;
--teal-300: #2C7A7B;
--teal-400: #319795;
--teal-500: #38B2AC;
--teal-600: #4FD1C5;
--teal-700: #81E6D9;
--teal-800: #B2F5EA;
--teal-900: #E6FFFA;
--white-alpha-50: rgba(255, 255, 255, 0.92);
--white-alpha-100: rgba(255, 255, 255, 0.80);
--white-alpha-200: rgba(255, 255, 255, 0.64);
--white-alpha-300: rgba(255, 255, 255, 0.48);
--white-alpha-400: rgba(255, 255, 255, 0.36);
--white-alpha-500: rgba(255, 255, 255, 0.24);
--white-alpha-600: rgba(255, 255, 255, 0.16);
--white-alpha-700: rgba(255, 255, 255, 0.08);
--white-alpha-800: rgba(255, 255, 255, 0.06);
--white-alpha-900: rgba(255, 255, 255, 0.04);
--yellow-50: #5F370E;
--yellow-100: #744210;
--yellow-200: #975A16;
--yellow-300: #B7791F;
--yellow-400: #D69E2E;
--yellow-500: #ECC94B;
--yellow-600: #F6E05E;
--yellow-700: #FAF089;
--yellow-800: #FEFCBF;
--yellow-900: #FFFFF0;
}
:root {
--black-alpha-50: rgba(0, 0, 0, 0.04);
--black-alpha-100: rgba(0, 0, 0, 0.06);
--black-alpha-200: rgba(0, 0, 0, 0.08);
--black-alpha-300: rgba(0, 0, 0, 0.16);
--black-alpha-400: rgba(0, 0, 0, 0.24);
--black-alpha-500: rgba(0, 0, 0, 0.36);
--black-alpha-600: rgba(0, 0, 0, 0.48);
--black-alpha-700: rgba(0, 0, 0, 0.64);
--black-alpha-800: rgba(0, 0, 0, 0.80);
--black-alpha-900: rgba(0, 0, 0, 0.92);
--blue-50: #ebf8ff;
--blue-100: #bee3f8;
--blue-200: #90cdf4;
--blue-300: #63b3ed;
--blue-400: #4299e1;
--blue-500: #3182ce;
--blue-600: #2b6cb0;
--blue-700: #2c5282;
--blue-800: #2a4365;
--blue-900: #1A365D;
--color-black: #000;
--color-white: #fff;
--cyan-50: #EDFDFD;
--cyan-100: #C4F1F9;
--cyan-200: #9DECF9;
--cyan-300: #76E4F7;
--cyan-400: #0BC5EA;
--cyan-500: #00B5D8;
--cyan-600: #00A3C4;
--cyan-700: #0987A0;
--cyan-800: #086F83;
--cyan-900: #065666;
--gray-50: #F7FAFC;
--gray-100: #EDF2F7;
--gray-200: #E2E8F0;
--gray-300: #CBD5E0;
--gray-400: #A0AEC0;
--gray-500: #718096;
--gray-600: #4A5568;
--gray-700: #2D3748;
--gray-800: #1A202C;
--gray-900: #171923;
--green-50: #F0FFF4;
--green-100: #C6F6D5;
--green-200: #9AE6B4;
--green-300: #68D391;
--green-400: #48BB78;
--green-500: #38A169;
--green-600: #2F855A;
--green-700: #276749;
--green-800: #22543D;
--green-900: #1C4532;
--orange-50: #FFFAF0;
--orange-100: #FEEBC8;
--orange-200: #FBD38D;
--orange-300: #F6AD55;
--orange-400: #ED8936;
--orange-500: #DD6B20;
--orange-600: #C05621;
--orange-700: #9C4221;
--orange-800: #7B341E;
--orange-900: #652B19;
--pink-50: #FFF5F7;
--pink-100: #FED7E2;
--pink-200: #FBB6CE;
--pink-300: #F687B3;
--pink-400: #ED64A6;
--pink-500: #D53F8C;
--pink-600: #B83280;
--pink-700: #97266D;
--pink-800: #702459;
--pink-900: #521B41;
--purple-50: #FAF5FF;
--purple-100: #E9D8FD;
--purple-200: #D6BCFA;
--purple-300: #B794F4;
--purple-400: #9F7AEA;
--purple-500: #805AD5;
--purple-600: #6B46C1;
--purple-700: #553C9A;
--purple-800: #44337A;
--purple-900: #322659;
--red-50: #FFF5F5;
--red-100: #FED7D7;
--red-200: #FEB2B2;
--red-300: #FC8181;
--red-400: #F56565;
--red-500: #E53E3E;
--red-600: #C53030;
--red-700: #9B2C2C;
--red-800: #822727;
--red-900: #63171B;
--teal-50: #E6FFFA;
--teal-100: #B2F5EA;
--teal-200: #81E6D9;
--teal-300: #4FD1C5;
--teal-400: #38B2AC;
--teal-500: #319795;
--teal-600: #2C7A7B;
--teal-700: #285E61;
--teal-800: #234E52;
--teal-900: #1D4044;
--white-alpha-50: rgba(255, 255, 255, 0.04);
--white-alpha-100: rgba(255, 255, 255, 0.06);
--white-alpha-200: rgba(255, 255, 255, 0.08);
--white-alpha-300: rgba(255, 255, 255, 0.16);
--white-alpha-400: rgba(255, 255, 255, 0.24);
--white-alpha-500: rgba(255, 255, 255, 0.36);
--white-alpha-600: rgba(255, 255, 255, 0.48);
--white-alpha-700: rgba(255, 255, 255, 0.64);
--white-alpha-800: rgba(255, 255, 255, 0.80);
--white-alpha-900: rgba(255, 255, 255, 0.92);
--yellow-50: #FFFFF0;
--yellow-100: #FEFCBF;
--yellow-200: #FAF089;
--yellow-300: #F6E05E;
--yellow-400: #ECC94B;
--yellow-500: #D69E2E;
--yellow-600: #B7791F;
--yellow-700: #975A16;
--yellow-800: #744210;
--yellow-900: #5F370E;
}
:root {
--font-size-12: 0.75rem;
--font-size-14: 0.875rem;
--font-size-16: 1rem;
--font-size-18: 1.125rem;
--font-size-20: 1.25rem;
--font-size-24: 1.5rem;
--font-size-30: 1.875rem;
--font-size-36: 2.25rem;
--font-size-48: 3rem;
--font-size-60: 3.75rem;
--font-size-72: 4.5rem;
--font-weight-400: 400;
--font-weight-500: 500;
--font-weight-600: 600;
--font-weight-700: 700;
--line-height-100: 100%;
--line-height-120: 120%;
--line-height-133: 133%;
--line-height-150: 150%;
}
.heading4xl {
font-size: 3.75rem;
font-weight: 700;
line-height: 100%;
}
.heading3xl {
font-size: 3rem;
font-weight: 700;
line-height: 100%;
}
.heading2xl {
font-size: 2.25rem;
font-weight: 700;
line-height: 120%;
}
.headingxl {
font-size: 1.875rem;
font-weight: 700;
line-height: 133%;
}
.headinglg {
font-size: 1.5rem;
font-weight: 700;
line-height: 133%;
}
.headingmd {
font-size: 1.25rem;
font-weight: 700;
line-height: 120%;
}
.headingsm {
font-size: 1rem;
font-weight: 700;
line-height: 120%;
}
.headingxs {
font-size: 0.875rem;
font-weight: 700;
line-height: 120%;
}
.text6xl {
font-size: 3.75rem;
font-weight: 400;
line-height: 150%;
}
.text5xl {
font-size: 3rem;
font-weight: 400;
line-height: 150%;
}
.text4xl {
font-size: 2.25rem;
font-weight: 400;
line-height: 150%;
}
.text3xl {
font-size: 1.875rem;
font-weight: 400;
line-height: 150%;
}
.text2xl {
font-size: 1.5rem;
font-weight: 400;
line-height: 150%;
}
.textxl {
font-size: 1.25rem;
font-weight: 400;
line-height: 150%;
}
.textlg {
font-size: 1.125rem;
font-weight: 400;
line-height: 150%;
}
.textmd {
font-size: 1rem;
font-weight: 400;
line-height: 150%;
}
.textsm {
font-size: 0.875rem;
font-weight: 400;
line-height: 150%;
}
.textxs {
font-size: 0.75rem;
font-weight: 400;
line-height: 150%;
}
```
